spring:
  profiles:
    active: dev
  
  flyway:
    enabled: true
    locations: classpath:db/migration/postgres
    baseline-on-migrate: true
    validate-on-migrate: false
    repair-on-migrate: true

app:
  jwtSecret: "your-very-secure-and-long-secret-key-should-be-at-least-64-characters-long"

server:
  port: 8080

logging:
  level:
    root: INFO
    com.example.taskapi: INFO
